apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spring-boot-deployment-two
spec:
  selector:
    matchLabels:
      app: ts-rest-service
  replicas: 2 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: ts-rest-service
    spec:
      containers:
      - name: ts-rest-service
        image: rzrbld/argocd-example-service:v1
        ports:
        - containerPort: 8080
          name: server
